name: Build & Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # If you have requirements.txt, uncomment the next line:
          pip install -r requirements.txt
      - name: Build app with PyInstaller
        run: |
          pyinstaller ./tchMaterial-parser.spec
          # The output binary will be in dist/tchMaterial-parser
          cd dist
          mv tchMaterial-parser.exe tchMaterial-parser-windows-x64.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/tchMaterial-parser-windows-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build Linux App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # If you have requirements.txt, uncomment the next line:
          pip install -r requirements.txt
      - name: Build app with PyInstaller
        run: |
          pyinstaller ./tchMaterial-parser.spec
          # The output binary will be in dist/tchMaterial-parser
          cd dist
          mv tchMaterial-parser tchMaterial-parser-linux-x64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/tchMaterial-parser-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # If you have requirements.txt, uncomment the next line:
          pip install -r requirements.txt
      - name: Build app with PyInstaller
        run: |
          pyinstaller ./tchMaterial-parser.spec
          # The output binary will be in dist/tchMaterial-parser
          cd dist
          mv tchMaterial-parser.app tchMaterial-parser-mac-arm64.app
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/tchMaterial-parser-mac-arm64.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
